### ISSUE TITLE
Resset učebnic

### ISSUE THREAD

**Issue by cinkim** [LenkaKonsty/slovnik_db#17]
Při přepnutí na jiného studenta zůstanou načtené původní učebnice.
Nutno nastavit výchozí nastavení pro načtení jazyka.

**Comment by LenkaKonsty** [comment]
Tady jsem opět ztracena v třídách a "dostupnosti" proměnných v různých funkcích....

self.ucebnice_ListBox  definuju ve funkci create_widgets_ucebnice, ale když jí chci použít v jiné funkci (pro tohle issue konkrétně funkce nacti_studenta, kde chci to vynulovat), tak to hlásí: AttributeError: 'slovnikGUI' object has no attribute 'ucebnice_ListBox'

tak nevím, kde a jak to má být definováno, voláno... :-(

zkoušela jsem jen do funkce nacti_studenta na začátek dát to vynulovaní (prozatím jen jednu položku):
self.ucebnice_ListBox.delete(0,1)

poradíte mi? ;-) Jsem marná

**Comment by cinkim** [comment]
musíš ve funkci create_widgets_jazyk nejprve ukončit Frame pro učebnice.
Pochopitelně to musíš upravit pro výjimky, protože při prvním načtení žádný Frame neexistuje, takže to spadne do AttributeError.

Já to udělal teď narychlo takto a vypadá to, že to funguje. Tak to tam dopiš. :-)
try:
    self.ucebnice.destroy()
except AttributeError:
    pass
for jazyk in self.jazyky_studenta:

**Comment by LenkaKonsty** [comment]
ok, vypadá to, že to funguje. testuju,  testuju...
