### ISSUE TITLE
Seznam studentů - změna aktuálního

### ISSUE THREAD

**Issue by LenkaKonsty** [LenkaKonsty/slovnik_db#22]
K zamyšlením případně doladit:

všechny seznamy (jazyky, učebnice, lekce) reagují hned po kliku a mění se podle toho související věci, jen načítání studenta k "akci" potřebuje stisk tlačítka "načti studenta".
Takže na to se snadno "zapomene" a pak nevšímavý uživatel (což jsou nejen děti) si může myslet že pracuje s daty studenta BBBB, protože na něm má aktuálně řádek, přitom naposledy měl načtenýho studenta AAAA.
Ano, píše se tam v nadpisu, o jakého studenta jde, ale... známe to.. klikání, klikání....

Takže mě napadají řešení, pokud se rozhodneme to upravit:
1) aby se po kliknutí na jiného studenta hned vše aktualizovalo a tedy zrušti tlačítko načti studenta
2) po kliknutí na jiného studenta všechna související pole (jazyky, učebnice, lekce) nulovat, odstranit

Může nám to nakopnout současný stav, ale myslím, že když už to máme takhle rozvětvený, že by se slušelo, aby to fungovalo intuitivně stejně.

Naopak tlačítko na "akci" bych dala po výběru lekce, momentálně to otvírá nekonečně oken pro testování.. .ale to počítám, že to je ve fázi rozpracovanosti a je to do jiného issues ;-)
Minimálně bych tam předchozí okno zavírala, když se otvírá další.

**Comment by cinkim** [comment]
Já mám obavy, že změna načítání studenta nám rozbije naprosto všechno. Už je tam strašně kódu a všechno souvisí se vším.
V tuto chvíli už bych do toho nesahal, alespoň mě se do toho nechce.
