### ISSUE TITLE
Tlačítko "Přidat novou učebnici"

### ISSUE THREAD

**Issue by cinkim** [LenkaKonsty/slovnik_db#26]
Navázat na nové okno, propojit na jazyk.
Zvážit jak zadávat nové lekce, zda rovnou s novou učebnicí, nebo....
Podle mě bude muset být další tlačítko "Přidat lekci", nejde spoléhat na to, že uživatel zadá všechny lekce.

**Comment by LenkaKonsty** [comment]
Jo, taky si myslim, ze lekce stejne se budou muset zadavat i zvlast...
Jestli to pujde tak max. v okne pro novou ucebnici dat tlacitko pro pridat lekci, ktery bude skakat do stejneho okna jako z hlavniho form.

**Comment by cinkim** [comment]
Ok. Jen úplně nevím jak na to.
Opět se to totiž odkazuje na všechno.
Ideálně na úvodní obrazovce vyžadovat při kliknutí na tlačítko mít vybraný jazyk.(Buď při kliknutí mesagebox"vyber jazyk", nebo jde tlačítko deaktivovat dokud nebude jazyk vybrán).
 Tím bude vidět seznam učebnic. V případě, že ve výběru nebude, může kliknout "Přidat učebnici" a přidání podmíníme založení alespoň jedné lekce.
Přidání lekce už by pak bylo podmíněné jazykem, a učebnicí.

**Comment by LenkaKonsty** [comment]
Nakonec jsem přidávání učebnice a lekce udělala odděleně, aby se nám formuláře moc nezanořovaly, protože pak by se muselo stejně "zanořit" a přidávání slovíček... a byl by to asi chaos
takže radši jednoduché formuláře.

Když je tam možnost přidat učebnici, měla by být možnost smazat učebnice, tak jsem trochu přeskládala tlačítka.
Editaci názvu učebnice bych už nedoplnovala. kdyžtak at si učebnici smaže a zadá novou. Předpokládám, že případnou editaci názvu učebnice by člověk potřeboval jen na začátku, při zadávání, kdy ještě učebnice nemá ani lekce ani slovíčka, takže smazáním si nenapáchá škody.

**Comment by cinkim** [comment]
Je opravdu dobry napad mazat ucebnici? Neodmaze se ucebnice, potazmo lekce a slovicka nahodou pro vsechny uzivatele?Odesláno z mého zařízení Galaxy
-------- Původní zpráva --------Od: Lenka Konstantinovičová ***@***.***> Datum: 17.04.21  20:11  (GMT+01:00) Komu: LenkaKonsty/slovnik_db ***@***.***> Cc: cinkim ***@***.***>, Author ***@***.***> Předmět: Re: [LenkaKonsty/slovnik_db] Tlačítko "Přidat novou učebnici" (#26) 

Nakonec jsem přidávání učebnice a lekce udělala odděleně, aby se nám formuláře moc nezanořovaly, protože pak by se muselo stejně "zanořit" a přidávání slovíček... a byl by to asi chaos

takže radši jednoduché formuláře.

Když je tam možnost přidat učebnici, měla by být možnost smazat učebnice, tak jsem trochu přeskládala tlačítka.

Editaci názvu učebnice bych už nedoplnovala. kdyžtak at si učebnici smaže a zadá novou. Předpokládám, že případnou editaci názvu učebnice by člověk potřeboval jen na začátku, při zadávání, kdy ještě učebnice nemá ani lekce ani slovíčka, takže smazáním si nenapáchá škody.

**Comment by LenkaKonsty** [comment]
Při mazání učebnice bych dovolila smazat jen učebnici, která nemá lekci ani slovíčka. Jinak ne. Jen jsem to myslela kvůli tomu, když si někdo zadá blbě název.
No  a nebo místo smazat učebnici dát jen editaci názvu.
A nebo se na to úplně vykašlat :-)

**Comment by cinkim** [comment]
Nez editaci, tak tam muzeme pred ulozenim dat otazku "Opravdu uožit?"  S navaznou odpovedi "Ano" "Ne"Odesláno z mého zařízení Galaxy
-------- Původní zpráva --------Od: Lenka Konstantinovičová ***@***.***> Datum: 17.04.21  21:17  (GMT+01:00) Komu: LenkaKonsty/slovnik_db ***@***.***> Cc: cinkim ***@***.***>, Author ***@***.***> Předmět: Re: [LenkaKonsty/slovnik_db] Tlačítko "Přidat novou učebnici" (#26) 

Při mazání učebnice bych dovolila smazat jen učebnici, která nemá lekci ani slovíčka. Jinak ne. Jen jsem to myslela kvůli tomu, když si někdo zadá blbě název.

No  a nebo místo smazat učebnici dát jen editaci názvu.

A nebo se na to úplně vykašlat :-)

**Comment by LenkaKonsty** [comment]
OK, zatím jsem to to teda pushla v té verzi bez otázky před uložením.
Pak se to opraví.
