### ISSUE TITLE
zápis výsledku testu do db

### ISSUE THREAD

**Issue by cinkim** [LenkaKonsty/slovnik_db#40]
vytvořit funkci pro zápis výsledku do db, kdy bude předáváno ["uzivatel", [ID slovíčka, informace o výsledku], [...........], [........]]
informace o výsledku bude mít hodnotu 0(špatná odpověď), nebo 1(správná odpověď) a přičte se k aktuální hodnotě daného slovíčka u daného uživatele.

**Comment by LenkaKonsty** [comment]
Tzn. že v rámci jednoho testu bude jedno konkrétní slovíčko zkoušet jen jednou, testovací funkce bude hlídat, aby random tam slovíčko nedal 2x?
Po ukončení testu (třeba 15slovíček dle nastavení) bych ještě rovnou vracela i nějaký výpočet úspešnosti (jakože známku) za daný test.... 

jedna věc je "výsledek testu k danému slovíčku" :  označení počtu, kolikrát už konkrétní slovíčka odpověděl správně
druhá věc je "výsledek testu jako celku"- hodnocení  jakože té sady testovaných slovíček, prostě to "oznámkovat" (procenta / známka /body)
- to bych taky uložila do db, takže rovnou v této funkci navrhuji předávat:
-  ["uzivatel", lekce_id, hodnoceni_testu, [ID slovíčka, informace o výsledku], [...........], [........]]

**Comment by cinkim** [comment]
Ještě jsem o tom tak úplně nepřemýšlel, ale viděl bych to tak, že testování převezme všechny slovíčka, zamíchá je a vezme prvních 20-30 slovíček která budou mít hodnotu menší než 3. Pak spustí 2x po sobě testování se stejnými slovíčky. Ve výsledku některá slovíčka budou mít hodnotu 2, jiná 1 a jiná 0. Tím se rychleji vyřadí z testování jednoduchá slovíčka. Pochopitelně pokud se vygeneruje slovíčko s hodnotou 2 a správně se odpoví v prvním kole testu, z druhého již bude vyřazen. 
Ale je to jen první úvaha.
Vyhodnocení testu pochopitelně vytvořit a uložit můžeme. Podle mě jsme to i plánovali s tím, že bude nějaký přístup do historie. Možná, když už to umíme i graf...? :-)

**Comment by LenkaKonsty** [comment]
:-) jasně, grafy, taková třešnička na dortu  :-)

funkci už mám, ale potřebuji si upřesnit:
počet správných odpovědí u daného slovíčka budeš posílat jako už koncové číslo, co se má zapsat do db, nebo jen počty v rámci daného testu a já si to v db dopočtu? JE mi to jedno, jen aby nám ty počty vycházely ;-)

Zatím to mám tak, že funkce si to dopočítává v rámci ukládání do db, tzn. seznam od tebe bude obsahovat počty odpovědí v rámci toho testu. Ale teď mě právě napadlo, že možná ty už budeš posílat rovnou ty celkový počty....
