### ISSUE TITLE
Ukládání slovíček

### ISSUE THREAD

**Issue by cinkim** [LenkaKonsty/slovnik_db#41]
Při prvním použití se do db automaticky načítají již nějaká slovíčka.
Nutno zajistit, aby se u nich uložila výchozí hodnota o počtu správných odpovědí.
Dále ověřit, zda se hodnota ukládá u slovíček zadávaných manuálně i importovaných z externích souborů.

**Comment by LenkaKonsty** [comment]
Tohle udelam trochu jinak(jeste přesně nevim jak) v db, protože ten pocet spravnych slovicek se vztahuje ke alovicku +studentovi, takze ty cisla správných slovicek buud resit nejspíš az ve chvíli, kdy si posles pozadavek na seznam slovicek...

Neco zkusim a uvidime, jak to bude fungovat a vyhovovat. Myslenku mám.

**Comment by cinkim** [comment]
jen info, požadavek bude vždy na všechny slovíčka lekce. Až poté si vyberu náhodně nějaký počet.
Takže do db pošlu požadavek [uživatel, jméno_lekce] a vrátit prosím [počet_sloviček_k_testování, [česky, překlad, počet_správných odpovědí], [..., ..., ...], [... , ... , ...]]

**Comment by LenkaKonsty** [comment]
Jo, s tim pocita, ze db bude vracet celou lekci, a pak dal se s tim bude delat co buse potreba...


Např. Pro vypis slovicek je taky potreba cela lekce.

**Comment by LenkaKonsty** [comment]
Tady jsem to rozdělila na dvě funkce:
nastaveni_studenta(student)  --> vrátí (zatím) dvojici (počet testovaných, počet správně odpovezených a kdy už netestovat), např. (20,3)
 tahle funkce se pak bude hodit na plnění formuláře pro nastavení studenta, podle potřeb ještě se bude upravovat a rozšiřovat...

slovicka_lekce(lekce, student) --> vrátí slovíčka lekce s počty odpovědí, viz  issues #42
