### ISSUE TITLE
slovíčka pro testování

### ISSUE THREAD

**Issue by cinkim** [LenkaKonsty/slovnik_db#42]
Vytvořit, připravit funkci v db, která vrátí všechny slovíčka dané lekce a uživatele:ID slovíčka, česky, překlad, počet správných odpovědí.

**Comment by LenkaKonsty** [comment]
upravena funkce: slovicka_lekce(lekce, student)

VSTUP: lekce - retezec
            student - retezec
VYSTUP: seznam slovicek [[id,cesky,preklad, spravne, spatne],[id,cesky,preklad, spravne, spatne],.... ]

Rovnou vrací i počty špatně odpovězených, ale zatím nemusíme využívat, ale udržovat tu hodnotu by byla analogie k počtu správně a pro přehled o slovíčkách mi to přijde dobrý.... :
Ve výpisu slovíček jsem to doplnila a je to pro přehled zajímavá informace, kolikrát co daný student odpověděl (správně/špatně)

Pokud s tím takhle budeš souhlasit, můžeme tohle issue uzavřít
