### ISSUE TITLE
Formulář Nastavení a ukládání do db

### ISSUE THREAD

**Issue by cinkim** [LenkaKonsty/slovnik_db#45]
Tak to shrneme, do nastavení dáme:
1.	Počet slovíček pro test(přednastavit 20)
2.	Počet správných odpovědí slovíček pro vyřazení(přednastavit 3) - pro vypnutí vyřazování bych volil hodnotu 0 "nula"
3.	Počet opakování testu se stejnými slovíčky(přednastavit 2)
4.	tři možnosti překladu pomocí radiobutton() - přednastavit míchat 
	tady bych volil v db ukládat číselné hodnoty, kde 1=cz/cizí, 2=cizí/cz, 3=míchat
5.	Testovat jen ze slovíček se špatnou odpovědí>3(přednastavit ne)
	opět 1=ano, 2=ne

**Comment by LenkaKonsty** [comment]
ok, jen to "přednastavit"  předpokládám znamená, že defaultně při registraci se to nastaví studentovi do db a danou hodnotu vždy se bere(bud brát) z db, ne z nastavení v kódu programu

**Comment by cinkim** [comment]
Přesně, nastavení se bude brát z db. V případě změny se nová data nejprve uloží do db a hned se zpětně načtou k okamžitému použití.
