### ISSUE TITLE
Základní data pro nové uživatele

### ISSUE THREAD

**Issue by LenkaKonsty** [LenkaKonsty/slovnik_db#65]
Upravit dle domluvy db_data.sql pro prvotní načtení db, aby tam byly ucelená data... učebnice se všemi lekcemi.

**Comment by cinkim** [comment]
Tady bych odmazal učebnici Project2. Mě se nějak nechce přepisovat všechna slovíčka, ale jestli má někdo spousty volného času, tak iniciativě meze nekladu. Já raději budu věnovat čas jinému projektu, než přepisovat slovíčka s vidinou, že ve škole má uživatel ve finále jinou učebnici.

**Comment by LenkaKonsty** [comment]
:-)

já to myslela tak, že já už ty slovíčka mám sepsaný, z toho mýho 
původního slovníku.
Abychom to teď plnily slovíčky to mě ani nenapadlo ;-)

---
_Lenka K._ 
Dne 2021-06-02 13:25, cinkim napsal:

> Tady bych odmazal učebnici Project2. Mě se nějak nechce přepisovat všechna slovíčka, ale jestli má někdo spousty volného času, tak iniciativě meze nekladu. Já raději budu věnovat čas jinému projektu, než přepisovat slovíčka s vidinou, že ve škole má uživatel ve finále jinou učebnici. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/LenkaKonsty/slovnik_db/issues/65#issuecomment-852946565
[2]

**Comment by cinkim** [comment]
pokud v této návaznosti nebudu muset nic předělávat, pouze odmažu soubor db_slovnik.sqlite a pak se sám vytvoří nový, tak proč ne.

**Comment by LenkaKonsty** [comment]
jo, když se rozhodneme, že budeme dodávat i slovíčka z Project2 (který
mám už napsaný), tak by to tak mohlo být, že se to načte v rámci prvního
vytvoření db.
Dávat to tam teď nemusíme,  a můžeme si to schovat do rozšířené verze
;-)

Pokud už bychom tuhle učebnici, nebo někdy jinou další (pokud by to
někdo měl naklikaný a chtěl poskytnout), tak už by se to muselo dělat
importem (mám nahrubo přripraveno), aby se mnemusela vytvářet nová db a
tím pádem celý uživatelský obsah db lidem smazat... ale to je zase o
dalších rozšířeních slovníku, samozřejmě

Dne 2021-06-02 14:01, cinkim napsal:

> pokud v této návaznosti nebudu muset nic předělávat, pouze odmažu soubor db_slovnik.sqlite a pak se sám vytvoří nový, tak proč ne. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/LenkaKonsty/slovnik_db/issues/65#issuecomment-852968329
[2]
