### ISSUE TITLE
Duplicita jména - velikost písmen  ??? 

### ISSUE THREAD

**Issue by LenkaKonsty** [LenkaKonsty/slovnik_db#8]
???? Rozlišovat nebo nerozlišovat velikost písmen ????

Za mě je teda "Student" stejný jako "student", pro jméno studenta. Ale asi záleží na úhlu pohledu, takže jak to vidíte vy?

Kontrolu duplicitního jména studenta bych ohlídala bez ohledu na velikosti písma... 
????

**Comment by cinkim** [comment]
Nevim zda až takto striktně posuzovat registraci. Tak přísně není řízená ani registrace emailu, či loginu do windows.

**Comment by LenkaKonsty** [comment]
Jakoze muzes mit jmeno Lenka a nekdo jinej lenka?Aha

Tak to teda beru zpět, já jsem databázově poznamenaná co se týče jedinečnosti asi jiank...
očividně SQLite je casesensitive, takže ok.

Vyber jazyků dle studenta mi funguje na Lenka i lenka, tak už mlčím

**Comment by cinkim** [comment]
To nemusis mlcet, jen mi to pride az moc prisny na program ktery ve finale budeme pouzivat my tri. Ale jestli ty mas poresena velka pismena v ramci sve funkce, tak uz nesmi projit registrace Lenka a lenka. Tva funkce by vracela stale stejne jazyky.
