### ISSUE TITLE
Zobrazení jazyků

### ISSUE THREAD

**Issue by cinkim** [LenkaKonsty/slovnik_db#9]
Vytvořit na úvodní stránce nějaké pole, kde se zobrazí vrácené studijní jazyky načteného studenta. Pole musí podporovat možnost výběru zazyka.

**Comment by LenkaKonsty** [comment]
Tak jsem to zkusila s ComboBoxem, jen nechápu, proč se to při indicatoron = 0 chová jinak (vybraný položky jako tlačítka) a v normálním provedení (zaškrtávací puntíky) to reaguje podivně.

S Tkinter tolik nemám zkušeností, tak s tím celkem bojuju, takže určitě to nebude ok, vím o místech, která  bych dělala jinak, ale tak to nefunguje :-( A určitě to jde líp.

Tak si nejsem jistá, jestli to má vůbec cenu dávat na GitHub.
Petře, předpokládám, že sis ten kód psal? ;-)

**Comment by cinkim** [comment]
Kdyz to nefunguje, tak to sem fakt nedavej.
Jeste jsem kod psat nezkousel, ale krome Treeview, ktere mam vyzkousene, bych nevedel do ceho jit. Proto jsem to chtel hodit na vas. Ale kdyz schovas ten prvni sloupec s tim indexovanim, tak to nevypada zas tak spatne.

**Comment by LenkaKonsty** [comment]
:-) no jasně, nefunkční  věc bych se nedávala.

funguje to, ale "nebude to ok" znamenalo spíš, že nevím, jestli je to zveřejnitelnej kód :-)

**Comment by cinkim** [comment]
Dej to do textaku a posli mi to emailem
